services:
  qemu:
    image: qemux/qemu
    container_name: qemu
    environment:
      BOOT: "https://archive.org/download/ubuntu-24.04.2-desktop-amd64/ubuntu-24.04.2-desktop-amd64.iso"
      RAM_SIZE: "4G"
      CPU_CORES: "2"
      DISK_SIZE: "64G"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - "8006:8006"
      - "3389:3389/tcp"
      - "3389:3389/udp"
    volumes:
      - ./qemu:/storage



