volumes:
  macos_main_data:
  macos_extra_data:

services:
  macos:
    image: dockurr/macos
    container_name: macos
    environment:
      VERSION: "https://archive.org/download/mac-os-15-sequoia-by-metaperso/Mac%20Os%2015%20Sequoia%20by%20Metaperso.iso"
      USERNAME: "User"
      RAM_SIZE: "4G"
      CPU_CORES: "2"
      DISK_SIZE: "20G"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - "8006:8006"
      - "3389:3389/tcp"
      - "3389:3389/udp"
    volumes:
      - macos_main_data:/data
      - macos_extra_data:/extra
