services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "10l"
      USERNAME: "User"
      PASSWORD: "user@123"
      RAM_SIZE: "4G"
      CPU_CORES: "2"
      DISK_SIZE: "20G"
      DISK2_SIZE: "2G"
    devices:
      - /dev/sdb:/disk1
      - /dev/sdc:/disk2
    cap_add:
      - NET_ADMIN
    ports:
      - "8006:8006"
      - "3389:3389/tcp"
      - "3389:3389/udp"
    volumes:
      - windows_main_data:/data
      - windows_extra_data:/extra
    stop_grace_period: 2m
