volumes:
  windows_main_data:
  windows_extra_data:

services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "https://archive.org/download/tiny11_25H2/tiny11_25H2_Oct25.iso"
      RAM_SIZE: "8G"
      CPU_CORES: "2"
      DISK_SIZE: "20G"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - "8006:8006"
      - "3389:3389/tcp"
      - "3389:3389/udp"
    volumes:
      - windows_main_data:/data
      - windows_extra_data:/extra



